services:
  web:
    build: .
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    volumes:
      - .:/minibanking
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    networks:
      - test
    command: uvicorn main:app --host 0.0.0.0 --port 8000
  redis:
    image: redis:latest
    container_name: myredis
    networks:
      - test
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
  worker:
    build: .
    volumes:
      - .:/minibanking
    networks:
      - test
    depends_on:
      - redis
    command: celery -A app.core.celery worker --loglevel=info
  db:
    image: postgres:17-alpine
    container_name: db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - test

networks:
  test:
    driver: bridge

volumes:
  postgres-data:
  redis-data: