"""Update field name for Account model

Revision ID: 5e4937cfa9fd
Revises: fe3f8a96bee7
Create Date: 2025-07-21 16:06:31.111847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e4937cfa9fd'
down_revision: Union[str, Sequence[str], None] = 'fe3f8a96bee7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
