"""Add email verifications fields

Revision ID: 830bdd5b95ae
Revises: ba80a45de55d
Create Date: 2025-08-24 17:24:17.246572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '830bdd5b95ae'
down_revision: Union[str, Sequence[str], None] = 'ba80a45de55d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email_verification_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email_verification_code_expires', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'email_verification_code_expires')
    op.drop_column('users', 'email_verification_code')
    op.drop_column('users', 'is_email_verified')
    # ### end Alembic commands ###
