"""Add user_id field in Transaction

Revision ID: 966341d503c2
Revises: 0e2b0ea8cb87
Create Date: 2025-08-10 19:00:27.741640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '966341d503c2'
down_revision: Union[str, Sequence[str], None] = '0e2b0ea8cb87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_transactions_user_id",
            "users",
            ["user_id"],
            ["id"]
        )

    op.execute("""
        UPDATE transactions
        SET user_id = accounts.user_id
        FROM accounts
        WHERE (transactions.from_account_id IS NULL AND transactions.to_account_id = accounts.id)
           OR transactions.from_account_id = accounts.id
    """)

    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.alter_column("user_id", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_constraint("fk_transactions_user_id", type_="foreignkey")
        batch_op.drop_column("user_id")
    # ### end Alembic commands ###
