"""Update field email_verification_code in User model

Revision ID: a1648c15abd7
Revises: 3a40a21fd7e8
Create Date: 2025-09-21 22:14:48.401755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1648c15abd7'
down_revision: Union[str, Sequence[str], None] = '3a40a21fd7e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email_verification_code',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using="email_verification_code::integer")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email_verification_code',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using="email_verification_code::varchar")
    # ### end Alembic commands ###
