"""Downgrade

Revision ID: ba80a45de55d
Revises: 966341d503c2
Create Date: 2025-08-24 17:20:52.069829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba80a45de55d'
down_revision: Union[str, Sequence[str], None] = '966341d503c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    op.drop_column('users', 'email_verified_code')
    op.drop_column('users', 'email_verified_code_expire')
    op.drop_column('users', 'is_email_verified')
    op.drop_column('users', 'emila_veritied_code_expire')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('emila_veritied_code_expire', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('is_email_verified', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=True))
    op.add_column('users', sa.Column('email_verified_code_expire', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('email_verified_code', sa.VARCHAR(length=6), nullable=True))
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=254), nullable=True))
    # ### end Alembic commands ###
