"""Add field name for Account model

Revision ID: fe3f8a96bee7
Revises: c53fddcf9060
Create Date: 2025-07-21 15:57:39.109284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe3f8a96bee7'
down_revision: Union[str, Sequence[str], None] = 'c53fddcf9060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('name', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'name')
    # ### end Alembic commands ###
